BEGIN TRANSACTION;

--
-- Roles
-- 1 - 2 - 4 - 8 
--
INSERT INTO roles (pk, rol) VALUES ('1','Estudiante');
INSERT INTO roles (pk, rol) VALUES ('2','Docente');
INSERT INTO roles (pk, rol) VALUES ('4','Empresa');
INSERT INTO roles (pk, rol) VALUES ('8','Administrador');


--
--  Datos de Regiones
--

INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de Arica y Parinacota','Norte Grande','XV','15');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de Tarapacá','Norte Grande','I','1');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de Antofagasta','Norte Grande','II','2');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de Atacama','Norte Chico','III','3');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de Coquimbo','Norte Chico','IV','4');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de Valparaíso','Núcleo Central','V','5');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región del Libertador General Bernardo O''Higgins','Núcleo Central','VI','6');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región del Maule','Núcleo Central','VII','7');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región del Biobío','Concepción y La Frontera','VIII','8');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de la Araucanía','Concepción y La Frontera','IX','9');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de los Ríos','Región de los Lagos','XIV','14');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de Los Lagos','Región de los Lagos','X','10');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de Aisén del General Carlos Ibáñez del Campo','Región de los Canales','XI','11');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región de Magallanes y de la Antártica Chilena','Región de los Canales','XII','12');
INSERT INTO regiones (nombre,zona_corfo,codigo,numero) VALUES ('Región Metropolitana de Santiago','Núcleo Central','RM','13');

--
-- Datos para provincias
--

INSERT INTO provincias (nombre,region_fk) VALUES ('Arica',(SELECT pk FROM regiones WHERE nombre='Región de Arica y Parinacota'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Parinacota',(SELECT pk FROM regiones WHERE nombre='Región de Arica y Parinacota'));
INSERT INTO provincias (nombre,region_fk) VALUES ('El Tamarugal',(SELECT pk FROM regiones WHERE nombre='Región de Tarapacá'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Iquique',(SELECT pk FROM regiones WHERE nombre='Región de Tarapacá'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Tocopilla',(SELECT pk FROM regiones WHERE nombre='Región de Antofagasta'));
INSERT INTO provincias (nombre,region_fk) VALUES ('El Loa',(SELECT pk FROM regiones WHERE nombre='Región de Antofagasta'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Antofagasta',(SELECT pk FROM regiones WHERE nombre='Región de Antofagasta'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Chañaral',(SELECT pk FROM regiones WHERE nombre='Región de Atacama'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Copiapó',(SELECT pk FROM regiones WHERE nombre='Región de Atacama'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Huasco',(SELECT pk FROM regiones WHERE nombre='Región de Atacama'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Elqui',(SELECT pk FROM regiones WHERE nombre='Región de Coquimbo'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Limarí',(SELECT pk FROM regiones WHERE nombre='Región de Coquimbo'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Choapa',(SELECT pk FROM regiones WHERE nombre='Región de Coquimbo'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Petorca',(SELECT pk FROM regiones WHERE nombre='Región de Valparaíso'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Los Andes',(SELECT pk FROM regiones WHERE nombre='Región de Valparaíso'));
INSERT INTO provincias (nombre,region_fk) VALUES ('San Felipe de Aconcagua',(SELECT pk FROM regiones WHERE nombre='Región de Valparaíso'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Quillota',(SELECT pk FROM regiones WHERE nombre='Región de Valparaíso'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Valparaíso',(SELECT pk FROM regiones WHERE nombre='Región de Valparaíso'));
INSERT INTO provincias (nombre,region_fk) VALUES ('San Antonio',(SELECT pk FROM regiones WHERE nombre='Región de Valparaíso'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Isla de Pascua',(SELECT pk FROM regiones WHERE nombre='Región de Valparaíso'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Cachapoal',(SELECT pk FROM regiones WHERE nombre='Región del Libertador General Bernardo O''Higgins'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Colchagua',(SELECT pk FROM regiones WHERE nombre='Región del Libertador General Bernardo O''Higgins'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Cardenal Caro',(SELECT pk FROM regiones WHERE nombre='Región del Libertador General Bernardo O''Higgins'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Curicó',(SELECT pk FROM regiones WHERE nombre='Región del Maule'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Talca',(SELECT pk FROM regiones WHERE nombre='Región del Maule'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Linares',(SELECT pk FROM regiones WHERE nombre='Región del Maule'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Cauquenes',(SELECT pk FROM regiones WHERE nombre='Región del Maule'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Ñuble',(SELECT pk FROM regiones WHERE nombre='Región del Biobío'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Biobío',(SELECT pk FROM regiones WHERE nombre='Región del Biobío'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Concepción',(SELECT pk FROM regiones WHERE nombre='Región del Biobío'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Arauco',(SELECT pk FROM regiones WHERE nombre='Región del Biobío'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Malleco',(SELECT pk FROM regiones WHERE nombre='Región de la Araucanía'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Cautín',(SELECT pk FROM regiones WHERE nombre='Región de la Araucanía'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Valdivia',(SELECT pk FROM regiones WHERE nombre='Región de los Ríos'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Ranco',(SELECT pk FROM regiones WHERE nombre='Región de los Ríos'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Osorno',(SELECT pk FROM regiones WHERE nombre='Región de Los Lagos'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Llanquihue',(SELECT pk FROM regiones WHERE nombre='Región de Los Lagos'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Chiloé',(SELECT pk FROM regiones WHERE nombre='Región de Los Lagos'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Palena',(SELECT pk FROM regiones WHERE nombre='Región de Los Lagos'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Coihaique',(SELECT pk FROM regiones WHERE nombre='Región de Aisén del General Carlos Ibáñez del Campo'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Aisén',(SELECT pk FROM regiones WHERE nombre='Región de Aisén del General Carlos Ibáñez del Campo'));
INSERT INTO provincias (nombre,region_fk) VALUES ('General Carrera',(SELECT pk FROM regiones WHERE nombre='Región de Aisén del General Carlos Ibáñez del Campo'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Capitán Prat',(SELECT pk FROM regiones WHERE nombre='Región de Aisén del General Carlos Ibáñez del Campo'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Última Esperanza',(SELECT pk FROM regiones WHERE nombre='Región de Magallanes y de la Antártica Chilena'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Magallanes',(SELECT pk FROM regiones WHERE nombre='Región de Magallanes y de la Antártica Chilena'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Tierra del Fuego',(SELECT pk FROM regiones WHERE nombre='Región de Magallanes y de la Antártica Chilena'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Antártica Chilena',(SELECT pk FROM regiones WHERE nombre='Región de Magallanes y de la Antártica Chilena'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Chacabuco',(SELECT pk FROM regiones WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Cordillera',(SELECT pk FROM regiones WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Maipo',(SELECT pk FROM regiones WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Talagante',(SELECT pk FROM regiones WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Melipilla',(SELECT pk FROM regiones WHERE nombre='Región Metropolitana de Santiago'));
INSERT INTO provincias (nombre,region_fk) VALUES ('Santiago',(SELECT pk FROM regiones WHERE nombre='Región Metropolitana de Santiago'));

--
-- Datos para las comunas.
--

INSERT INTO comunas (nombre,provincia_fk) VALUES ('Arica',(SELECT pk FROM provincias WHERE nombre='Arica'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Camarones',(SELECT pk FROM provincias WHERE nombre='Arica'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('General Lagos',(SELECT pk FROM provincias WHERE nombre='Parinacota'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Putre',(SELECT pk FROM provincias WHERE nombre='Parinacota'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Camiña',(SELECT pk FROM provincias WHERE nombre='El Tamarugal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Colchane',(SELECT pk FROM provincias WHERE nombre='El Tamarugal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Huara',(SELECT pk FROM provincias WHERE nombre='El Tamarugal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pica',(SELECT pk FROM provincias WHERE nombre='El Tamarugal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pozo Almonte',(SELECT pk FROM provincias WHERE nombre='El Tamarugal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Iquique',(SELECT pk FROM provincias WHERE nombre='Iquique'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Alto Hospicio',(SELECT pk FROM provincias WHERE nombre='Iquique'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('María Elena',(SELECT pk FROM provincias WHERE nombre='Tocopilla'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Tocopilla',(SELECT pk FROM provincias WHERE nombre='Tocopilla'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Calama',(SELECT pk FROM provincias WHERE nombre='El Loa'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Ollagüe',(SELECT pk FROM provincias WHERE nombre='El Loa'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Pedro de Atacama',(SELECT pk FROM provincias WHERE nombre='El Loa'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Antofagasta',(SELECT pk FROM provincias WHERE nombre='Antofagasta'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Mejillones',(SELECT pk FROM provincias WHERE nombre='Antofagasta'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Sierra Gorda',(SELECT pk FROM provincias WHERE nombre='Antofagasta'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Taltal',(SELECT pk FROM provincias WHERE nombre='Antofagasta'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chañaral',(SELECT pk FROM provincias WHERE nombre='Chañaral'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Diego de Almagro',(SELECT pk FROM provincias WHERE nombre='Chañaral'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Copiapó',(SELECT pk FROM provincias WHERE nombre='Copiapó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Caldera',(SELECT pk FROM provincias WHERE nombre='Copiapó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Tierra Amarilla',(SELECT pk FROM provincias WHERE nombre='Copiapó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Vallenar',(SELECT pk FROM provincias WHERE nombre='Huasco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Freirina',(SELECT pk FROM provincias WHERE nombre='Huasco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Huasco',(SELECT pk FROM provincias WHERE nombre='Huasco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Alto del Carmen',(SELECT pk FROM provincias WHERE nombre='Huasco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Andacollo',(SELECT pk FROM provincias WHERE nombre='Elqui'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Coquimbo',(SELECT pk FROM provincias WHERE nombre='Elqui'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Higuera',(SELECT pk FROM provincias WHERE nombre='Elqui'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Serena',(SELECT pk FROM provincias WHERE nombre='Elqui'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Paihuano',(SELECT pk FROM provincias WHERE nombre='Elqui'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Vicuña',(SELECT pk FROM provincias WHERE nombre='Elqui'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Ovalle',(SELECT pk FROM provincias WHERE nombre='Limarí'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Río Hurtado',(SELECT pk FROM provincias WHERE nombre='Limarí'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Monte Patria',(SELECT pk FROM provincias WHERE nombre='Limarí'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Combarbalá',(SELECT pk FROM provincias WHERE nombre='Limarí'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Punitaqui',(SELECT pk FROM provincias WHERE nombre='Limarí'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Illapel',(SELECT pk FROM provincias WHERE nombre='Choapa'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Salamanca',(SELECT pk FROM provincias WHERE nombre='Choapa'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Los Vilos',(SELECT pk FROM provincias WHERE nombre='Choapa'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Canela',(SELECT pk FROM provincias WHERE nombre='Choapa'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Ligua',(SELECT pk FROM provincias WHERE nombre='Petorca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cabildo',(SELECT pk FROM provincias WHERE nombre='Petorca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Zapallar',(SELECT pk FROM provincias WHERE nombre='Petorca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Papudo',(SELECT pk FROM provincias WHERE nombre='Petorca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Petorca',(SELECT pk FROM provincias WHERE nombre='Petorca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Los Andes',(SELECT pk FROM provincias WHERE nombre='Los Andes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Esteban',(SELECT pk FROM provincias WHERE nombre='Los Andes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Calle Larga',(SELECT pk FROM provincias WHERE nombre='Los Andes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Rinconada',(SELECT pk FROM provincias WHERE nombre='Los Andes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Felipe',(SELECT pk FROM provincias WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Llaillay',(SELECT pk FROM provincias WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Putaendo',(SELECT pk FROM provincias WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Santa María',(SELECT pk FROM provincias WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Catemu',(SELECT pk FROM provincias WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Panquehue',(SELECT pk FROM provincias WHERE nombre='San Felipe de Aconcagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quillota',(SELECT pk FROM provincias WHERE nombre='Quillota'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Calera',(SELECT pk FROM provincias WHERE nombre='Quillota'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Limache',(SELECT pk FROM provincias WHERE nombre='Quillota'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Nogales',(SELECT pk FROM provincias WHERE nombre='Quillota'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Hijuelas',(SELECT pk FROM provincias WHERE nombre='Quillota'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Olmué',(SELECT pk FROM provincias WHERE nombre='Quillota'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Cruz',(SELECT pk FROM provincias WHERE nombre='Quillota'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Valparaíso',(SELECT pk FROM provincias WHERE nombre='Valparaíso'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Viña del Mar',(SELECT pk FROM provincias WHERE nombre='Valparaíso'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quilpué',(SELECT pk FROM provincias WHERE nombre='Valparaíso'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Villa Alemana',(SELECT pk FROM provincias WHERE nombre='Valparaíso'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Concón',(SELECT pk FROM provincias WHERE nombre='Valparaíso'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quintero',(SELECT pk FROM provincias WHERE nombre='Valparaíso'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Puchuncaví',(SELECT pk FROM provincias WHERE nombre='Valparaíso'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Casablanca',(SELECT pk FROM provincias WHERE nombre='Valparaíso'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Juan Fernández',(SELECT pk FROM provincias WHERE nombre='Valparaíso'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Algarrobo',(SELECT pk FROM provincias WHERE nombre='San Antonio'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('El Quisco',(SELECT pk FROM provincias WHERE nombre='San Antonio'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('El Tabo',(SELECT pk FROM provincias WHERE nombre='San Antonio'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cartagena',(SELECT pk FROM provincias WHERE nombre='San Antonio'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Antonio',(SELECT pk FROM provincias WHERE nombre='San Antonio'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Santo Domingo',(SELECT pk FROM provincias WHERE nombre='San Antonio'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Isla de Pascua',(SELECT pk FROM provincias WHERE nombre='Isla de Pascua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Codegua',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Coínco',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Coltauco',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Doñihue',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Graneros',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Las Cabras',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Machalí',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Malloa',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Olivar',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Peumo',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pichidegua',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quinta de Tilcoco',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Rancagua',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Requínoa',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Rengo',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Mostazal',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Vicente de Tagua Tagua',(SELECT pk FROM provincias WHERE nombre='Cachapoal'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chépica',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chimbarongo',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lolol',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Nancagua',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Palmilla',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Peralillo',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Placilla',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pumanque',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Fernando',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Santa Cruz',(SELECT pk FROM provincias WHERE nombre='Colchagua'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Estrella',(SELECT pk FROM provincias WHERE nombre='Cardenal Caro'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Litueche',(SELECT pk FROM provincias WHERE nombre='Cardenal Caro'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Marchigüe',(SELECT pk FROM provincias WHERE nombre='Cardenal Caro'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Navidad',(SELECT pk FROM provincias WHERE nombre='Cardenal Caro'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Paredones',(SELECT pk FROM provincias WHERE nombre='Cardenal Caro'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pichilemu',(SELECT pk FROM provincias WHERE nombre='Cardenal Caro'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Curicó',(SELECT pk FROM provincias WHERE nombre='Curicó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Hualañé',(SELECT pk FROM provincias WHERE nombre='Curicó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Licantén',(SELECT pk FROM provincias WHERE nombre='Curicó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Molina',(SELECT pk FROM provincias WHERE nombre='Curicó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Rauco',(SELECT pk FROM provincias WHERE nombre='Curicó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Romeral',(SELECT pk FROM provincias WHERE nombre='Curicó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Sagrada Familia',(SELECT pk FROM provincias WHERE nombre='Curicó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Teno',(SELECT pk FROM provincias WHERE nombre='Curicó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Vichuquén',(SELECT pk FROM provincias WHERE nombre='Curicó'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Talca',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Clemente',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pelarco',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pencahue',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Maule',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Rafael',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Curepto',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Constitución',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Empedrado',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Río Claro',(SELECT pk FROM provincias WHERE nombre='Talca'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Linares',(SELECT pk FROM provincias WHERE nombre='Linares'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Javier de Loncomilla',(SELECT pk FROM provincias WHERE nombre='Linares'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Parral',(SELECT pk FROM provincias WHERE nombre='Linares'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Villa Alegre',(SELECT pk FROM provincias WHERE nombre='Linares'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Longaví',(SELECT pk FROM provincias WHERE nombre='Linares'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Colbún',(SELECT pk FROM provincias WHERE nombre='Linares'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Retiro',(SELECT pk FROM provincias WHERE nombre='Linares'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Yerbas Buenas',(SELECT pk FROM provincias WHERE nombre='Linares'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cauquenes',(SELECT pk FROM provincias WHERE nombre='Cauquenes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chanco',(SELECT pk FROM provincias WHERE nombre='Cauquenes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pelluhue',(SELECT pk FROM provincias WHERE nombre='Cauquenes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Bulnes',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chillán',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chillán Viejo',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cobquecura',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Coelemu',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Coihueco',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('El Carmen',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Ninhue',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Ñiquén',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pemuco',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pinto',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Portezuelo',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quillón',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quirihue',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Ránquil',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Carlos',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Fabián',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Ignacio',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Nicolás',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Treguaco',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Yungay',(SELECT pk FROM provincias WHERE nombre='Ñuble'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Alto Biobío',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Antuco',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cabrero',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Laja',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Los Ángeles',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Mulchén',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Nacimiento',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Negrete',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quilaco',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quilleco',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Rosendo',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Santa Bárbara',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Tucapel',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Yumbel',(SELECT pk FROM provincias WHERE nombre='Biobío'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Concepción',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Coronel',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chiguayante',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Florida',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Hualpén',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Hualqui',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lota',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Penco',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Pedro de la Paz',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Santa Juana',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Talcahuano',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Tomé',(SELECT pk FROM provincias WHERE nombre='Concepción'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Arauco',(SELECT pk FROM provincias WHERE nombre='Arauco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cañete',(SELECT pk FROM provincias WHERE nombre='Arauco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Contulmo',(SELECT pk FROM provincias WHERE nombre='Arauco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Curanilahue',(SELECT pk FROM provincias WHERE nombre='Arauco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lebu',(SELECT pk FROM provincias WHERE nombre='Arauco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Los Álamos',(SELECT pk FROM provincias WHERE nombre='Arauco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Tirúa',(SELECT pk FROM provincias WHERE nombre='Arauco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Angol',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Collipulli',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Curacautín',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Ercilla',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lonquimay',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Los Sauces',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lumaco',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Purén',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Renaico',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Traiguén',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Victoria',(SELECT pk FROM provincias WHERE nombre='Malleco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Temuco',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Carahue',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cholchol',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cunco',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Curarrehue',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Freire',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Galvarino',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Gorbea',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lautaro',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Loncoche',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Melipeuco',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Nueva Imperial',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Padre Las Casas',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Perquenco',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pitrufquén',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pucón',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Saavedra',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Teodoro Schmidt',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Toltén',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Vilcún',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Villarrica',(SELECT pk FROM provincias WHERE nombre='Cautín'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Valdivia',(SELECT pk FROM provincias WHERE nombre='Valdivia'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Corral',(SELECT pk FROM provincias WHERE nombre='Valdivia'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lanco',(SELECT pk FROM provincias WHERE nombre='Valdivia'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Los Lagos',(SELECT pk FROM provincias WHERE nombre='Valdivia'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Mariquina',(SELECT pk FROM provincias WHERE nombre='Valdivia'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Máfil',(SELECT pk FROM provincias WHERE nombre='Valdivia'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Paillaco',(SELECT pk FROM provincias WHERE nombre='Valdivia'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Panguipulli',(SELECT pk FROM provincias WHERE nombre='Valdivia'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Unión',(SELECT pk FROM provincias WHERE nombre='Ranco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Futrono',(SELECT pk FROM provincias WHERE nombre='Ranco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lago Ranco',(SELECT pk FROM provincias WHERE nombre='Ranco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Río Bueno',(SELECT pk FROM provincias WHERE nombre='Ranco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Osorno',(SELECT pk FROM provincias WHERE nombre='Osorno'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Puerto Octay',(SELECT pk FROM provincias WHERE nombre='Osorno'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Purranque',(SELECT pk FROM provincias WHERE nombre='Osorno'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Puyehue',(SELECT pk FROM provincias WHERE nombre='Osorno'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Río Negro',(SELECT pk FROM provincias WHERE nombre='Osorno'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Pablo',(SELECT pk FROM provincias WHERE nombre='Osorno'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Juan de la Costa',(SELECT pk FROM provincias WHERE nombre='Osorno'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Calbuco',(SELECT pk FROM provincias WHERE nombre='Llanquihue'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cochamó',(SELECT pk FROM provincias WHERE nombre='Llanquihue'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Fresia',(SELECT pk FROM provincias WHERE nombre='Llanquihue'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Frutillar',(SELECT pk FROM provincias WHERE nombre='Llanquihue'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Llanquihue',(SELECT pk FROM provincias WHERE nombre='Llanquihue'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Los Muermos',(SELECT pk FROM provincias WHERE nombre='Llanquihue'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Maullín',(SELECT pk FROM provincias WHERE nombre='Llanquihue'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Puerto Montt',(SELECT pk FROM provincias WHERE nombre='Llanquihue'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Puerto Varas',(SELECT pk FROM provincias WHERE nombre='Llanquihue'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Ancud',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Castro',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chonchi',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Curaco de Vélez',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Dalcahue',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Puqueldón',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Queilén',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quellón',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quemchi',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quinchao',(SELECT pk FROM provincias WHERE nombre='Chiloé'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chaitén',(SELECT pk FROM provincias WHERE nombre='Palena'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Futaleufú',(SELECT pk FROM provincias WHERE nombre='Palena'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Hualaihué',(SELECT pk FROM provincias WHERE nombre='Palena'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Palena',(SELECT pk FROM provincias WHERE nombre='Palena'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Coihaique',(SELECT pk FROM provincias WHERE nombre='Coihaique'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lago Verde',(SELECT pk FROM provincias WHERE nombre='Coihaique'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Aisén',(SELECT pk FROM provincias WHERE nombre='Aisén'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cisnes',(SELECT pk FROM provincias WHERE nombre='Aisén'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Guaitecas',(SELECT pk FROM provincias WHERE nombre='Aisén'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Chile Chico',(SELECT pk FROM provincias WHERE nombre='General Carrera'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Río Ibáñez',(SELECT pk FROM provincias WHERE nombre='General Carrera'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cochrane',(SELECT pk FROM provincias WHERE nombre='Capitán Prat'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('O''Higgins',(SELECT pk FROM provincias WHERE nombre='Capitán Prat'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Tortel',(SELECT pk FROM provincias WHERE nombre='Capitán Prat'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Natales',(SELECT pk FROM provincias WHERE nombre='Última Esperanza'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Torres del Paine',(SELECT pk FROM provincias WHERE nombre='Última Esperanza'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Laguna Blanca',(SELECT pk FROM provincias WHERE nombre='Magallanes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Punta Arenas',(SELECT pk FROM provincias WHERE nombre='Magallanes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Río Verde',(SELECT pk FROM provincias WHERE nombre='Magallanes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Gregorio',(SELECT pk FROM provincias WHERE nombre='Magallanes'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Porvenir',(SELECT pk FROM provincias WHERE nombre='Tierra del Fuego'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Primavera',(SELECT pk FROM provincias WHERE nombre='Tierra del Fuego'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Timaukel',(SELECT pk FROM provincias WHERE nombre='Tierra del Fuego'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cabo de Hornos',(SELECT pk FROM provincias WHERE nombre='Antártica Chilena'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Antártica',(SELECT pk FROM provincias WHERE nombre='Antártica Chilena'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Colina',(SELECT pk FROM provincias WHERE nombre='Chacabuco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lampa',(SELECT pk FROM provincias WHERE nombre='Chacabuco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Tiltil',(SELECT pk FROM provincias WHERE nombre='Chacabuco'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Puente Alto',(SELECT pk FROM provincias WHERE nombre='Cordillera'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San José de Maipo',(SELECT pk FROM provincias WHERE nombre='Cordillera'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pirque',(SELECT pk FROM provincias WHERE nombre='Cordillera'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Bernardo',(SELECT pk FROM provincias WHERE nombre='Maipo'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Buin',(SELECT pk FROM provincias WHERE nombre='Maipo'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Paine',(SELECT pk FROM provincias WHERE nombre='Maipo'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Calera de Tango',(SELECT pk FROM provincias WHERE nombre='Maipo'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Isla de Maipo',(SELECT pk FROM provincias WHERE nombre='Talagante'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('El Monte',(SELECT pk FROM provincias WHERE nombre='Talagante'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Padre Hurtado',(SELECT pk FROM provincias WHERE nombre='Talagante'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Peñaflor',(SELECT pk FROM provincias WHERE nombre='Talagante'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Talagante',(SELECT pk FROM provincias WHERE nombre='Talagante'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Curacaví',(SELECT pk FROM provincias WHERE nombre='Melipilla'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('María Pinto',(SELECT pk FROM provincias WHERE nombre='Melipilla'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Melipilla',(SELECT pk FROM provincias WHERE nombre='Melipilla'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Pedro',(SELECT pk FROM provincias WHERE nombre='Melipilla'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Alhué',(SELECT pk FROM provincias WHERE nombre='Melipilla'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cerrillos',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Cerro Navia',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Conchalí',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('El Bosque',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Estación Central',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Huechuraba',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Independencia',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Cisterna',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Granja',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Florida',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Pintana',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('La Reina',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Las Condes',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lo Barnechea',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lo Espejo',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Lo Prado',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Macul',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Maipú',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Ñuñoa',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pedro Aguirre Cerda',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Peñalolén',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Providencia',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Pudahuel',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quilicura',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Quinta Normal',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Recoleta',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Renca',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Miguel',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Joaquín',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('San Ramón',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Santiago',(SELECT pk FROM provincias WHERE nombre='Santiago'));
INSERT INTO comunas (nombre,provincia_fk) VALUES ('Vitacura',(SELECT pk FROM provincias WHERE nombre='Santiago'));

--
-- Facultades
--
INSERT INTO facultades (facultad) VALUES ('Humanidades y Tecnologías de la Comunicación Social');
INSERT INTO facultades (facultad) VALUES ('Ciencias de la Construcción y Ordenamiento Territorial');
INSERT INTO facultades (facultad) VALUES ('Ciencias Naturales, Matemática y del Medio Ambiente');
INSERT INTO facultades (facultad) VALUES ('Administración y Economía');
INSERT INTO facultades (facultad) VALUES ('Ingeniería');

--
-- Departamentos
--
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('1','Diseño');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('1','Cartografía');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('1','Trabajo Social');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('1','Humanidades');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('2','Prevención de Riesgos y Medioambiente');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('2','Ciencias de la Construcción');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('2','Planificación y Ordenamiento Territorial');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('3','Química');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('3','Matemática');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('3','Física');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('3','Biotecnología');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('4','Gestión Organizacional');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('4','Economía, Recursos Naturales y Comercio Internacional');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('4','Contabilidad y Gestión Financiera');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('4','Gestión de la Información');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('4','Estadística y Econometría');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('5','Industria');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('5','Informática y Computación');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('5','Electricidad');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('5','Mecánica');
INSERT INTO departamentos (facultad_fk, departamento) VALUES ('5','Sin departamento asociado');

--
-- Escuelas
--
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('1','Diseño');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('2','Cartografía');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('3','Trabajo Social');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('4','Criminalística Forense');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('5','Prevención de Riesgos y Medio Ambiente');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('6','Construcción Civil');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('7','Arquitectura');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('8','Química');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('8','Ingeniería en Industria Alimentaria');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('12','Administración');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('13','Comercio Internacional');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('14','Contadores Auditores');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('15','Bibliotecología');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('16','Ingeniería Comercial');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('18','Informática');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('17','Industria');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('17','Ingeniería en Industria de la Madera');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('17','Geomensura');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('17','Transporte y Tránsito');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('19','Electrónica');
INSERT INTO escuelas (departamento_fk, escuela) VALUES ('20','Mecánica');

--
-- Carreras
--

INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21002','Bibliotecología y Documentación',(SELECT pk FROM escuelas WHERE escuela='Bibliotecología'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21004','Cartografía',(SELECT pk FROM escuelas WHERE escuela='Cartografía'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21012','Contador Público y Auditor',(SELECT pk FROM escuelas WHERE escuela='Contadores Auditores'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21015','Ingeniería en Administración Agroindustrial',(SELECT pk FROM escuelas WHERE escuela='Administración'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21023','Diseño Industrial',(SELECT pk FROM escuelas WHERE escuela='Diseño'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21024','Diseño en Comunicación Visual',(SELECT pk FROM escuelas WHERE escuela='Diseño'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21025','Ingeniería en Transporte y Tránsito',(SELECT pk FROM escuelas WHERE escuela='Transporte y Tránsito'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21030','Ingeniería en Informática',(SELECT pk FROM escuelas WHERE escuela='Informática'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21031','Ingeniería en Geomensura',(SELECT pk FROM escuelas WHERE escuela='Geomensura'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21032','Ingeniería en Construcción',(SELECT pk FROM escuelas WHERE escuela='Construcción Civil'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21036','Ingeniería en Electrónica',(SELECT pk FROM escuelas WHERE escuela='Electrónica'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21037','Ingeniería en Mecánica',(SELECT pk FROM escuelas WHERE escuela='Mecánica'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21038','Ingeniería en Industria de la Madera',(SELECT pk FROM escuelas WHERE escuela='Ingeniería en Industria de la Madera'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21039','Ingeniería en Industria Alimentaria',(SELECT pk FROM escuelas WHERE escuela='Ingeniería en Industria Alimentaria'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21040','Ingeniería Civil Industrial mención Agroindustria',(SELECT pk FROM escuelas WHERE escuela='Industria'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21041','Ingeniería Civil en Computación con Mención en Informática',(SELECT pk FROM escuelas WHERE escuela='Informática'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21042','Ingeniería en Prevención de Riesgos y Medioambiente',(SELECT pk FROM escuelas WHERE escuela='Prevención de Riesgos y Medio Ambiente'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21043','Trabajo Social',(SELECT pk FROM escuelas WHERE escuela='Trabajo Social'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21044','Ingeniería Civil Industrial mención Sistemas de Gestión',(SELECT pk FROM escuelas WHERE escuela='Industria'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21045','Ingeniería Industrial',(SELECT pk FROM escuelas WHERE escuela='Industria'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21046','Bachillerato en Ciencias de la Ingeniería',(SELECT pk FROM escuelas WHERE escuela='Industria'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21047','Arquitectura',(SELECT pk FROM escuelas WHERE escuela='Arquitectura'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21048','Ingeniería Comercial',(SELECT pk FROM escuelas WHERE escuela='Ingeniería Comercial'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21071','Dibujante Proyectista',(SELECT pk FROM escuelas WHERE escuela='Industria'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21073','Ingeniería en Biotecnología',(SELECT pk FROM escuelas WHERE escuela='Química'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21074','Ingeniería Civil en Obras Civiles',(SELECT pk FROM escuelas WHERE escuela='Construcción Civil'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21080','Ingeniería en Química',(SELECT pk FROM escuelas WHERE escuela='Química'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21081','Ingeniería en Comercio Internacional',(SELECT pk FROM escuelas WHERE escuela='Comercio Internacional'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21082','Ingeniería en Gestión Turística',(SELECT pk FROM escuelas WHERE escuela='Comercio Internacional'));
INSERT INTO carreras (cod_carrera, nombre_carrera, escuela_fk) VALUES ('21083','Química Industrial',(SELECT pk FROM escuelas WHERE escuela='Química'));

--
-- Estados Civiles
--
INSERT INTO estados_civiles (estado) VALUES ('Soltero(a)');
INSERT INTO estados_civiles (estado) VALUES ('Casado(a)');
INSERT INTO estados_civiles (estado) VALUES ('Separado(a)');
INSERT INTO estados_civiles (estado) VALUES ('Viudo(a)');
INSERT INTO estados_civiles (estado) VALUES ('Sin datos');

-- 
-- Rubros
-- 
INSERT INTO rubros (rubro) VALUES ('Abastecimiento');
INSERT INTO rubros (rubro) VALUES ('Administración');
INSERT INTO rubros (rubro) VALUES ('Administración Pública');
INSERT INTO rubros (rubro) VALUES ('Aduanas');
INSERT INTO rubros (rubro) VALUES ('Agronomía');
INSERT INTO rubros (rubro) VALUES ('Alimentos y Bebidas');
INSERT INTO rubros (rubro) VALUES ('Ambiental');
INSERT INTO rubros (rubro) VALUES ('Amparo');
INSERT INTO rubros (rubro) VALUES ('Arquitectura');
INSERT INTO rubros (rubro) VALUES ('Aseo');
INSERT INTO rubros (rubro) VALUES ('Asistente y Secretaria');
INSERT INTO rubros (rubro) VALUES ('Auditoría');
INSERT INTO rubros (rubro) VALUES ('Automatización / Instrumentación');
INSERT INTO rubros (rubro) VALUES ('Banca y Servicios Financieros');
INSERT INTO rubros (rubro) VALUES ('Bursátil');
INSERT INTO rubros (rubro) VALUES ('Cadena de Suministro');
INSERT INTO rubros (rubro) VALUES ('Calidad');
INSERT INTO rubros (rubro) VALUES ('Call Center');
INSERT INTO rubros (rubro) VALUES ('Capacitación');
INSERT INTO rubros (rubro) VALUES ('Clinica');
INSERT INTO rubros (rubro) VALUES ('Cobranza');
INSERT INTO rubros (rubro) VALUES ('Comedores Industriales');
INSERT INTO rubros (rubro) VALUES ('Comercial');
INSERT INTO rubros (rubro) VALUES ('Comercio Exterior');
INSERT INTO rubros (rubro) VALUES ('Compras');
INSERT INTO rubros (rubro) VALUES ('Computación e Informática');
INSERT INTO rubros (rubro) VALUES ('Comunicación / Medios');
INSERT INTO rubros (rubro) VALUES ('Comunicación Audiovisual');
INSERT INTO rubros (rubro) VALUES ('Comunicación Institucional');
INSERT INTO rubros (rubro) VALUES ('Confección');
INSERT INTO rubros (rubro) VALUES ('Construcción');
INSERT INTO rubros (rubro) VALUES ('Contabilidad');
INSERT INTO rubros (rubro) VALUES ('Contaduría');
INSERT INTO rubros (rubro) VALUES ('Contraloría');
INSERT INTO rubros (rubro) VALUES ('Control de Calidad');
INSERT INTO rubros (rubro) VALUES ('Control de Gestión');
INSERT INTO rubros (rubro) VALUES ('Corporativa');
INSERT INTO rubros (rubro) VALUES ('Costura');
INSERT INTO rubros (rubro) VALUES ('Crédito');
INSERT INTO rubros (rubro) VALUES ('Cuentas clave');
INSERT INTO rubros (rubro) VALUES ('Decoración');
INSERT INTO rubros (rubro) VALUES ('Derecho');
INSERT INTO rubros (rubro) VALUES ('Derecho Administrativo');
INSERT INTO rubros (rubro) VALUES ('Derecho Aduanero');
INSERT INTO rubros (rubro) VALUES ('Derecho Bancario y Bursátil');
INSERT INTO rubros (rubro) VALUES ('Derecho Civil');
INSERT INTO rubros (rubro) VALUES ('Derecho Constitucional');
INSERT INTO rubros (rubro) VALUES ('Derecho Electoral');
INSERT INTO rubros (rubro) VALUES ('Derecho Energético');
INSERT INTO rubros (rubro) VALUES ('Derecho Familiar');
INSERT INTO rubros (rubro) VALUES ('Derecho Financiero');
INSERT INTO rubros (rubro) VALUES ('Derecho Internacional');
INSERT INTO rubros (rubro) VALUES ('Derecho Laboral');
INSERT INTO rubros (rubro) VALUES ('Derecho Mercantil');
INSERT INTO rubros (rubro) VALUES ('Derecho Notarial');
INSERT INTO rubros (rubro) VALUES ('Derecho Penal');
INSERT INTO rubros (rubro) VALUES ('Derechos Humanos');
INSERT INTO rubros (rubro) VALUES ('Desarrollo');
INSERT INTO rubros (rubro) VALUES ('Desarrollo de Producto');
INSERT INTO rubros (rubro) VALUES ('Despacho');
INSERT INTO rubros (rubro) VALUES ('Dibujante');
INSERT INTO rubros (rubro) VALUES ('Digitadores');
INSERT INTO rubros (rubro) VALUES ('Dirección en servicios de salud');
INSERT INTO rubros (rubro) VALUES ('Dirección General');
INSERT INTO rubros (rubro) VALUES ('Diseño');
INSERT INTO rubros (rubro) VALUES ('Diseño Audiovisual');
INSERT INTO rubros (rubro) VALUES ('Diseño de Confecciones');
INSERT INTO rubros (rubro) VALUES ('Diseño Industrial');
INSERT INTO rubros (rubro) VALUES ('Distribución');
INSERT INTO rubros (rubro) VALUES ('Docencia');
INSERT INTO rubros (rubro) VALUES ('Economía');
INSERT INTO rubros (rubro) VALUES ('Edición/Redacción');
INSERT INTO rubros (rubro) VALUES ('Edificación');
INSERT INTO rubros (rubro) VALUES ('Editorialismo médico');
INSERT INTO rubros (rubro) VALUES ('Educación / Docencia');
INSERT INTO rubros (rubro) VALUES ('Educación Física');
INSERT INTO rubros (rubro) VALUES ('Educación médica');
INSERT INTO rubros (rubro) VALUES ('Electricidad');
INSERT INTO rubros (rubro) VALUES ('Electrónica');
INSERT INTO rubros (rubro) VALUES ('Empaque');
INSERT INTO rubros (rubro) VALUES ('Envasado');
INSERT INTO rubros (rubro) VALUES ('Epidemiología');
INSERT INTO rubros (rubro) VALUES ('Estética');
INSERT INTO rubros (rubro) VALUES ('Estimulación temprana');
INSERT INTO rubros (rubro) VALUES ('Estudio');
INSERT INTO rubros (rubro) VALUES ('Facturación');
INSERT INTO rubros (rubro) VALUES ('Finanzas');
INSERT INTO rubros (rubro) VALUES ('Fiscal');
INSERT INTO rubros (rubro) VALUES ('Fotografía');
INSERT INTO rubros (rubro) VALUES ('Gastronomía');
INSERT INTO rubros (rubro) VALUES ('Gerencia');
INSERT INTO rubros (rubro) VALUES ('Gestión');
INSERT INTO rubros (rubro) VALUES ('Hospitalaria');
INSERT INTO rubros (rubro) VALUES ('Hoteles');
INSERT INTO rubros (rubro) VALUES ('Idiomas');
INSERT INTO rubros (rubro) VALUES ('Ilustración de Figurín');
INSERT INTO rubros (rubro) VALUES ('Impuestos');
INSERT INTO rubros (rubro) VALUES ('Informática');
INSERT INTO rubros (rubro) VALUES ('Informática &ndash; hardware');
INSERT INTO rubros (rubro) VALUES ('Informática &ndash; internet');
INSERT INTO rubros (rubro) VALUES ('Ingeniería');
INSERT INTO rubros (rubro) VALUES ('Inteligencia de Negocios');
INSERT INTO rubros (rubro) VALUES ('Internet');
INSERT INTO rubros (rubro) VALUES ('Inversión Extranjera');
INSERT INTO rubros (rubro) VALUES ('Inversiones');
INSERT INTO rubros (rubro) VALUES ('Investigación');
INSERT INTO rubros (rubro) VALUES ('Investigación clínica');
INSERT INTO rubros (rubro) VALUES ('Investigación de mercados');
INSERT INTO rubros (rubro) VALUES ('Laboratorio');
INSERT INTO rubros (rubro) VALUES ('Leyes');
INSERT INTO rubros (rubro) VALUES ('Litigio');
INSERT INTO rubros (rubro) VALUES ('Logística');
INSERT INTO rubros (rubro) VALUES ('Mantención');
INSERT INTO rubros (rubro) VALUES ('Marketing / Mercadeo');
INSERT INTO rubros (rubro) VALUES ('Mecánica');
INSERT INTO rubros (rubro) VALUES ('Medicina y Salud');
INSERT INTO rubros (rubro) VALUES ('Medio Ambiente');
INSERT INTO rubros (rubro) VALUES ('Medios de información');
INSERT INTO rubros (rubro) VALUES ('Mercadotecnia');
INSERT INTO rubros (rubro) VALUES ('Negocios Internacionales');
INSERT INTO rubros (rubro) VALUES ('Nóminas');
INSERT INTO rubros (rubro) VALUES ('Operaciones');
INSERT INTO rubros (rubro) VALUES ('Organización de eventos');
INSERT INTO rubros (rubro) VALUES ('Orientación');
INSERT INTO rubros (rubro) VALUES ('Otra Área');
INSERT INTO rubros (rubro) VALUES ('Patronaje');
INSERT INTO rubros (rubro) VALUES ('Periodismo');
INSERT INTO rubros (rubro) VALUES ('Planificación y Desarrollo');
INSERT INTO rubros (rubro) VALUES ('Post Venta');
INSERT INTO rubros (rubro) VALUES ('Precios de transferencia');
INSERT INTO rubros (rubro) VALUES ('Prevención de Riesgos');
INSERT INTO rubros (rubro) VALUES ('Producción y Manufactura');
INSERT INTO rubros (rubro) VALUES ('Promociones');
INSERT INTO rubros (rubro) VALUES ('Propiedad Industrial e Intelectual');
INSERT INTO rubros (rubro) VALUES ('Propiedades');
INSERT INTO rubros (rubro) VALUES ('Proyectos');
INSERT INTO rubros (rubro) VALUES ('Psicopedagógica');
INSERT INTO rubros (rubro) VALUES ('Publicidad');
INSERT INTO rubros (rubro) VALUES ('Química');
INSERT INTO rubros (rubro) VALUES ('Recepción');
INSERT INTO rubros (rubro) VALUES ('Reclutamiento y Selección');
INSERT INTO rubros (rubro) VALUES ('Recursos Humanos');
INSERT INTO rubros (rubro) VALUES ('Redes y Telecomunicaciones');
INSERT INTO rubros (rubro) VALUES ('Relaciones Públicas');
INSERT INTO rubros (rubro) VALUES ('Salud');
INSERT INTO rubros (rubro) VALUES ('Salud Pública');
INSERT INTO rubros (rubro) VALUES ('Secretaria Bilingue');
INSERT INTO rubros (rubro) VALUES ('Seguridad e Higiene');
INSERT INTO rubros (rubro) VALUES ('Seguros');
INSERT INTO rubros (rubro) VALUES ('Servicio al Cliente');
INSERT INTO rubros (rubro) VALUES ('Servicio Técnico');
INSERT INTO rubros (rubro) VALUES ('Servicios');
INSERT INTO rubros (rubro) VALUES ('Servicios de Seguridad');
INSERT INTO rubros (rubro) VALUES ('Servicios Generales');
INSERT INTO rubros (rubro) VALUES ('Servicios Sociales');
INSERT INTO rubros (rubro) VALUES ('Sociedades Mercantiles');
INSERT INTO rubros (rubro) VALUES ('Soporte Administrativo');
INSERT INTO rubros (rubro) VALUES ('Suministros');
INSERT INTO rubros (rubro) VALUES ('Tecnologías de Información');
INSERT INTO rubros (rubro) VALUES ('Telecomunicaciones');
INSERT INTO rubros (rubro) VALUES ('Teléfonos');
INSERT INTO rubros (rubro) VALUES ('Telemarketing');
INSERT INTO rubros (rubro) VALUES ('Todas las Areas');
INSERT INTO rubros (rubro) VALUES ('Trade Marketing');
INSERT INTO rubros (rubro) VALUES ('Tributarios');
INSERT INTO rubros (rubro) VALUES ('Turismo y Hotelería');
INSERT INTO rubros (rubro) VALUES ('Ventas');
INSERT INTO rubros (rubro) VALUES ('Veterinaria');


-- 
-- Niveles de Estudios
-- 
INSERT INTO niveles_estudios (estudios) VALUES ('Sin estudios');
INSERT INTO niveles_estudios (estudios) VALUES ('Básica Incompleta');
INSERT INTO niveles_estudios (estudios) VALUES ('Básica Completa');
INSERT INTO niveles_estudios (estudios) VALUES ('Media Incompleta');
INSERT INTO niveles_estudios (estudios) VALUES ('Media Completa');
INSERT INTO niveles_estudios (estudios) VALUES ('Centro de Formación Técnica Incompleta');
INSERT INTO niveles_estudios (estudios) VALUES ('Centro de Formación Técnica Completa');
INSERT INTO niveles_estudios (estudios) VALUES ('Universitaria Incompleta');
INSERT INTO niveles_estudios (estudios) VALUES ('Universitario Completa');
INSERT INTO niveles_estudios (estudios) VALUES ('PostTítulo');
INSERT INTO niveles_estudios (estudios) VALUES ('Otros Estudios');

--
-- Estados
--
INSERT INTO estados (nombre) VALUES ('Regular');
INSERT INTO estados (nombre) VALUES ('Egreso');
INSERT INTO estados (nombre) VALUES ('Titulado');
INSERT INTO estados (nombre) VALUES ('Traslado');
INSERT INTO estados (nombre) VALUES ('Fallecido');
INSERT INTO estados (nombre) VALUES ('Eliminado');
INSERT INTO estados (nombre) VALUES ('Moroso');
INSERT INTO estados (nombre) VALUES ('Transferido');
INSERT INTO estados (nombre) VALUES ('Sin inscripción');
INSERT INTO estados (nombre) VALUES ('Abandono Voluntario');
INSERT INTO estados (nombre) VALUES ('Renuncia');
INSERT INTO estados (nombre) VALUES ('Postergado');
INSERT INTO estados (nombre) VALUES ('Permiso');

COMMIT;
